# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Gamma_int <- function(v_0, v_1, p_1, p_2, p, k, Theta_l) {
    .Call(`_superviseNet_Gamma_int`, v_0, v_1, p_1, p_2, p, k, Theta_l)
}

